// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDg5fXYhYRe8s94oO5aiQORnka91QgE0cg',
    appId: '1:603127940453:web:a5724e999fdd071b92cd8c',
    messagingSenderId: '603127940453',
    projectId: 'quiz-49bdc',
    authDomain: 'quiz-49bdc.firebaseapp.com',
    storageBucket: 'quiz-49bdc.appspot.com',
    measurementId: 'G-RFWRLR1V5J',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBisC1Csog8QVSYrV31TYEKTGpJy44B2ls',
    appId: '1:603127940453:android:f98e03f71c41f9c492cd8c',
    messagingSenderId: '603127940453',
    projectId: 'quiz-49bdc',
    storageBucket: 'quiz-49bdc.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCr4jKTHHUmWvrcGzqWewrokKa6r5qpgDM',
    appId: '1:603127940453:ios:bdad90833353e29892cd8c',
    messagingSenderId: '603127940453',
    projectId: 'quiz-49bdc',
    storageBucket: 'quiz-49bdc.appspot.com',
    iosBundleId: 'com.example.issPrep',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCr4jKTHHUmWvrcGzqWewrokKa6r5qpgDM',
    appId: '1:603127940453:ios:925010160647ea1e92cd8c',
    messagingSenderId: '603127940453',
    projectId: 'quiz-49bdc',
    storageBucket: 'quiz-49bdc.appspot.com',
    iosBundleId: 'com.example.issPrep.RunnerTests',
  );
}
